//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUBiblioPelis
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class pelicula
    {
        [ScaffoldColumn(false)]
        public int idpelicula { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Los nombres son requeridos"), MaxLength(55)]
        [Display(Name = "Nombre")]
        public string nombre { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "La categoría es requerida"), MaxLength(55)]
        [Display(Name = "Categoria")]
        public string categoria { get; set; }
        
        [Display(Name = "Fecha")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> fecha_lanz { get; set; }
        
        [Required(ErrorMessage = "Los minutos de duración son requeridos")]
        [Display(Name = "Minutos")]
        
        public Nullable<int> duracion_min { get; set; }
    }
}
